Remove the energy parameter from commandline
Make the stencil examples consistently hardcode the energy parameter.

Exception: accelerators/, mpi_io/, and tools/ examples are left alone
and they need to be updated in the future. Likely they should reuse the
routines in stencil_par.c rather than have their own copies.